# Generated by Django 5.2.1 on 2025-05-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_white', models.CharField(default='white', max_length=100)),
                ('player_black', models.CharField(default='black', max_length=100)),
                ('is_draw', models.BooleanField(default=False)),
                ('winner', models.BooleanField(blank=True, choices=[('white', 'White'), ('black', 'Black')], max_length=100, null=True)),
                ('board_state', models.CharField(max_length=300)),
            ],
        ),
    ]
