# Generated by Django 5.2.1 on 2025-07-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=100)),
                ('move', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_square', models.CharField(blank=True, max_length=2, null=True)),
                ('to_square', models.CharField(blank=True, max_length=2, null=True)),
                ('piece', models.CharField(blank=True, max_length=10, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
            ],
        ),
    ]
